# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
    RUST_VERSION: stable
    PROJECT_NAME: rypt

  matrix:
    # MinGW
#    - TARGET: i686-pc-windows-gnu
#    - TARGET: x86_64-pc-windows-gnu

    # MSVC
#    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc
      FRIENDLY_TARGET_NAME: windows-x86_64

    # Testing other channels
#    - TARGET: x86_64-pc-windows-gnu
#      RUST_VERSION: nightly
#    - TARGET: x86_64-pc-windows-msvc
#      RUST_VERSION: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  # we don't run the "test phase" when doing deploys
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET% --release &&
      cargo test --target %TARGET% --release &&
      cargo run --target %TARGET% --release -- --version
    )

before_deploy:
  - cargo rustc --target %TARGET% --release --bins -- -C lto
  - ps: ci\before_deploy.ps1

deploy:
  - artifact: /.*\.zip/
    auth_token:
      secure: qWDXszRXbGzhtHi9+Z4fRzRWpSW+XsK6IWXXPgTmgfSPSNRvEvPv+hHG57btbqMc
    description: ''
    on:
      appveyor_repo_tag: true
    provider: GitHub
    force_update: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
