[package]
name = "rypt"
version = "0.2.0"
authors = ["Alexander Shtuchkin <ashtuchkin@gmail.com>"]
edition = "2018"

#description = "..."
#repository = "..."
#homepage = "..."
#documentation = "..."

license = "MIT"


[dependencies]
libsodium-sys = "0.2.2"
prost = "0.5.*"
bytes = "0.4.*"
crossbeam-channel = "0.3.*"
getopts = "0.2.*"
failure = "0.1.*"

# isatty, clear line, password input
termion = "1.5.0"

[profile.release]
lto = true