[package]
name = "rust-crypto-test"
version = "0.1.0"
authors = ["Alexander Shtuchkin <ashtuchkin@gmail.com>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.*"
structopt = "0.2.*"
failure = "0.1.*"
term = "0.5.*"
humansize = "1.1.*"
crossbeam-channel = "0.3.*"
libsodium-sys = "0.2.2"
prost = "0.5.*"
bytes = "0.4.*"

[profile.release]
lto = true